name = "tg-assistant-worker"
main = "worker.js"
compatibility_date = "2025-08-24"

# Привязка существующего KV (production)
# ВСТАВИТЬ реальный Namespace ID (даст владелец репо перед merge)
[[kv_namespaces]]
binding = "KV"
id = "31abe783382f4a17883cb17ea713cdc2"
